image: node:16

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules

build-pages:
  stage: build
  script:
    - rm -rf build
    - yarn install
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r build/. public/
  artifacts:
    paths:
      - public

deploy-to-ec2:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y openssh-client
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/private_key
    - ssh-add /tmp/private_key
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 13.213.43.166 >> ~/.ssh/known_hosts
    - scp -r -o StrictHostKeyChecking=no public/ ubuntu@ec2-13-213-43-166.ap-southeast-1.compute.amazonaws.com:/var/www/html
  only:
    - main  # Deploy only when changes are pushed to the master branch
